In [1]:
from pathlib import Path
import numpy as np

DATA_ROOT = Path("../data/sample/processed")

instance_labels = np.load(
    DATA_ROOT /
    "stage_4_instance_segmentation" /
    "instance_labels.npy"
)

print("Shape :", instance_labels.shape)
print("Dtype :", instance_labels.dtype)
print("Cells :", instance_labels.max())

Shape : (64, 256, 256)
Dtype : int32
Cells : 199

In [2]:
from skimage.measure import regionprops_table
import pandas as pd

properties = regionprops_table(
    instance_labels,
    properties=[
        "label",
        "centroid",
        "area",
        "bbox",
    ],
)

cells_df = pd.DataFrame(properties)

cells_df.head()

,label,centroid-0,centroid-1,centroid-2,area,bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5
0,1,0.231183,6.354839,52.204301,186.0,0,0,46,2,14,60
1,2,0.153153,6.815315,71.774775,222.0,0,0,65,2,16,80
2,3,0.320833,26.012500,65.191667,240.0,0,18,59,4,35,72
3,4,1.074627,62.743555,58.230665,737.0,0,55,48,4,72,68
4,5,0.364431,98.571429,34.836735,343.0,0,89,28,2,109,43

In [3]:
cells_df = cells_df.rename(
    columns={
        "label": "cell_id",
        "centroid-0": "centroid_z",
        "centroid-1": "centroid_y",
        "centroid-2": "centroid_x",
        "area": "volume_voxels",
        "bbox-0": "z_min",
        "bbox-1": "y_min",
        "bbox-2": "x_min",
        "bbox-3": "z_max",
        "bbox-4": "y_max",
        "bbox-5": "x_max",
    }
)

cells_df.head()

,cell_id,centroid_z,centroid_y,centroid_x,volume_voxels,z_min,y_min,x_min,z_max,y_max,x_max
0,1,0.231183,6.354839,52.204301,186.0,0,0,46,2,14,60
1,2,0.153153,6.815315,71.774775,222.0,0,0,65,2,16,80
2,3,0.320833,26.012500,65.191667,240.0,0,18,59,4,35,72
3,4,1.074627,62.743555,58.230665,737.0,0,55,48,4,72,68
4,5,0.364431,98.571429,34.836735,343.0,0,89,28,2,109,43

In [4]:
print(f"Detected cells : {len(cells_df)}")

display(cells_df.head())

print(cells_df.describe())

Detected cells : 199

,cell_id,centroid_z,centroid_y,centroid_x,volume_voxels,z_min,y_min,x_min,z_max,y_max,x_max
0,1,0.231183,6.354839,52.204301,186.0,0,0,46,2,14,60
1,2,0.153153,6.815315,71.774775,222.0,0,0,65,2,16,80
2,3,0.320833,26.012500,65.191667,240.0,0,18,59,4,35,72
3,4,1.074627,62.743555,58.230665,737.0,0,55,48,4,72,68
4,5,0.364431,98.571429,34.836735,343.0,0,89,28,2,109,43

          cell_id  centroid_z  centroid_y  centroid_x  volume_voxels  \
count  199.000000  199.000000  199.000000  199.000000     199.000000
mean   100.000000   32.018861  132.255936  148.012180     762.613065
std     57.590508   19.169983   76.909325   58.697818     419.290377
min      1.000000    0.000000    0.557692   27.429688      52.000000
25%     50.500000   15.651869   62.036393  100.482441     488.500000
50%    100.000000   32.800234  138.347212  150.037736     753.000000
75%    149.500000   49.052671  198.070781  195.754561    1017.500000
max    199.000000   63.000000  254.118280  253.891892    2374.000000

            z_min       y_min       x_min       z_max       y_max       x_max
count  199.000000  199.000000  199.000000  199.000000  199.000000  199.000000
mean    29.874372  124.376884  140.170854   35.201005  141.130653  156.854271
std     19.062876   76.981394   58.908600   19.172523   76.581725   58.432676
min      0.000000    0.000000   21.000000    1.000000    3.000000   33.000000
25%     14.000000   53.500000   92.000000   18.500000   73.000000  110.000000
50%     30.000000  129.000000  141.000000   36.000000  146.000000  160.000000
75%     46.500000  191.000000  188.500000   52.000000  207.000000  203.000000
max     63.000000  252.000000  252.000000   64.000000  256.000000  256.000000

In [5]:
from pathlib import Path

OUTPUT_DIR = Path(
    "../data/sample/processed/stage_5_cell_detection"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

cells_df.to_csv(
    OUTPUT_DIR / "cells.csv",
    index=False,
)

print("Saved:", OUTPUT_DIR / "cells.csv")

Saved: ..\data\sample\processed\stage_5_cell_detection\cells.csv